# fly.toml app configuration file generated for tatiatic-webapp on 2023-08-07T17:04:02+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tatiatic-webapp"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8051
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 3
  processes = ["app"]
